//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xeber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public int news_id { get; set; }
        public string title { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public bool accept { get; set; }
        public int like { get; set; }
        public int unlike { get; set; }
        public string photo { get; set; }
    
        public virtual news news { get; set; }
    }
}
