//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xeber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string text { get; set; }
    }
}
