//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xeber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchang
    {
        public int id { get; set; }
        public string name { get; set; }
        public string buying { get; set; }
        public string sales { get; set; }
    }
}
