//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xeber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public news()
        {
            this.comment = new HashSet<comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public int category_id { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public string writer { get; set; }
        public int type_id { get; set; }
        public int picCount { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        public virtual type type { get; set; }
    }
}
