//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xeber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int id { get; set; }
        public string logo { get; set; }
        public string flogo { get; set; }
        public string advertsment { get; set; }
        public string fadvertsment { get; set; }
        public string location { get; set; }
        public string email { get; set; }
        public string phono { get; set; }
    }
}
